### ISSUE TITLE
Write README

### ISSUE THREAD

**Issue by andrew-monroe** [GitGud-KU/Skeddit#19]
- Describe our application and how it is used.
- Describe how to view our documentation and how it was created.

**Comment by andrew-monroe** [comment]
Also we need to have a works cited, but for the most part that is our imported stuff like gems and bootstrap and whatnot. Maybe we could just say cite rails, bootstrap, and then direct them to the Gemfile to view our other sources? Let me know what you guys think

**Comment by zbruennig** [comment]
Still need documentation and an official works cited section for it, but I'm making a separate issue for that.
